<a href="https://colab.research.google.com/github/SARRAMBO/ASSIGNMENTS_PYTHON/blob/main/TelecomSalesEDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cufflinks as cf
cf.go_offline()

In [2]:
#FETCH DATA-
df = pd.read_csv("/telecom_data.csv")
print(df)

             Alliance Partner Division  Alliance Partner Division Code  \
0                           7-11 - AUS                             656
1                           7-11 - AUS                             656
2                           7-11 - AUS                             656
3                           7-11 - AUS                             656
4                           7-11 - AUS                             656
...                                ...                             ...
206614  WOOLWORTHS GROCERY - AUSTRALIA                            1052
206615  WOOLWORTHS GROCERY - AUSTRALIA                            1052
206616  WOOLWORTHS GROCERY - AUSTRALIA                            1052
206617  WOOLWORTHS GROCERY - AUSTRALIA                            1052
206618  WOOLWORTHS GROCERY - AUSTRALIA                            1052

       Card Partner Division                          Product  \
0         LEBARA - AUSTRALIA   LEBARA STARTER KIT LG 39.90AUD
1         LEBARA - AUSTRALIA  LEBARA STARTER KIT MED 29.90AUD
2         LEBARA - AUSTRALIA  LEBARA STARTER KIT MED 29.90AUD
3         LEBARA - AUSTRALIA  LEBARA STARTER KIT MED 29.90AUD
4         LEBARA - AUSTRALIA   LEBARA STARTER KIT XS 14.90AUD
...                      ...                              ...
206614          VODAFONE SIM  VODAFONE SIM TRIPLE PUNCH 40AUD
206615          VODAFONE SIM  VODAFONE SIM TRIPLE PUNCH 40AUD
206616          VODAFONE SIM  VODAFONE SIM TRIPLE PUNCH 40AUD
206617          VODAFONE SIM  VODAFONE SIM TRIPLE PUNCH 40AUD
206618          VODAFONE SIM  VODAFONE SIM TRIPLE PUNCH 40AUD

                                         Store Store Code       Date  \
0                7ELEVEN-Yarraville1119 - 1119      01119   1-1-2023
1         7ELEVEN-Melbourne Central1121 - 1121      01121   1-1-2023
2                 7ELEVEN-Haymarket2071 - 2071      02071   1-1-2023
3                        7 ELEVEN-02308 - 2308      02308   1-1-2023
4                   7ELEVEN-Lakemba2268 - 2268      02268   1-1-2023
...                                        ...        ...        ...
206614       Woolworths Clayton M City - 03806       3806  8-12-2023
206615  Woolworths St. Georges Terrace - 04301       4301  8-12-2023
206616     Woolworths Mandurah Central - 04340       4340  8-12-2023
206617              Woolworths Gateways - 4394       4394  8-12-2023
206618            Woolworths Northpark - 05687       5687  8-12-2023

        Fiscal Week   Month  Fiscal Year  Sales Units Sales Amount-Non USD  \
0            202301  202301         2023            1               39.90
1            202301  202301         2023            1               29.90
2            202301  202301         2023            2               59.80
3            202301  202301         2023            1               29.90
4            202301  202301         2023            1               14.90
...             ...     ...          ...          ...                  ...
206614       202332  202308         2023            1               40.00
206615       202332  202308         2023            2               80.00
206616       202332  202308         2023            1               40.00
206617       202332  202308         2023            2               80.00
206618       202332  202308         2023            1               40.00

          month  day  week_no
0       January    1        1
1       January    1        1
2       January    1        1
3       January    1        1
4       January    1        1
...         ...  ...      ...
206614   August   12       32
206615   August   12       32
206616   August   12       32
206617   August   12       32
206618   August   12       32

[206619 rows x 15 columns]

<ipython-input-2-f21fbdc884cd>:1: DtypeWarning:

Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.

In [12]:
#column info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206619 entries, 0 to 206618
Data columns (total 15 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Alliance Partner Division       206619 non-null  object
 1   Alliance Partner Division Code  206619 non-null  int64
 2   Card Partner Division           206619 non-null  object
 3   Product                         206619 non-null  object
 4   Store                           206619 non-null  object
 5   Store Code                      206619 non-null  object
 6   Date                            206619 non-null  object
 7   Fiscal Week                     206619 non-null  int64
 8   Month                           206619 non-null  int64
 9   Fiscal Year                     206619 non-null  int64
 10  Sales Units                     206619 non-null  int64
 11  Sales Amount-Non USD            206619 non-null  object
 12  month                           206619 non-null  object
 13  day                             206619 non-null  int64
 14  week_no                         206619 non-null  int64
dtypes: int64(7), object(8)
memory usage: 23.6+ MB

In [16]:
#obtaining numerical columns info-
df.describe()
#obtaining categorical columns info-
df[df.dtypes[df.dtypes=="object"].index].describe()

,Alliance Partner Division,Card Partner Division,Product,Store,Store Code,Date,Sales Amount-Non USD,month
count,206619,206619,206619,206619,206619,206619,206619,206619
unique,12,2,21,5862,9401,224,245,8
top,WOOLWORTHS GROCERY - AUSTRALIA,VODAFONE SIM,VODAFONE SIM TRIPLE PUNCH 2AUD,Coles World Square - 00710,92007,4-8-2023,2.00,July
freq,85117,147109,27863,1005,627,1124,46560,30586

In [1]:
df.dtypes
df["revenue"] =df["Sales Units"]*df["Sales Amount-Non USD"]

NameError: name 'df' is not defined